### ISSUE TITLE
SSL+SNI: Set OpenSSL::SSL::SSLSocket#hostname for shared hosts

### ISSUE THREAD

**Issue by ryannhos** [rocketjob/net_tcp_client#13]
https://ruby-doc.org/stdlib-2.4.0/libdoc/openssl/rdoc/OpenSSL/SSL/SSLSocket.html#method-i-hostname-3D

When two SSL-enabled hostnames are served from the same IP, the SSL socket needs to use SNI (Server Name Indication) to tell the webserver which cert should be used for the conversation.  This needs to be done before calling `OpenSSL::SSL::SSLSocket#connect`.

Add it right about here: https://github.com/rocketjob/net_tcp_client/blob/master/lib/net/tcp_client/tcp_client.rb#L683

Expect a PR shortly...

**Comment by reidmorrison** [comment]
Thank you for the PR
